### ISSUE TITLE
unigrams support

### ISSUE THREAD

**Issue by thanasions** [datasciencecampus/pyGrams#100]
At the moment unigrams are not supported as they cannot produce sensible results. Need to find a way round it so that we could pick up terms like blockchain for example. One idea is to look at emergence in timeseries. A more generic option though would be better (ie. no timeseries dependent. feature selection algs?)

**Comment by emily-tew** [comment]
My plan is to try and eliminate terms which are roughly linear based on cumulative counts over time as this should rule out common terms. Don't think it is worth looking at the emergence trend as this is dealt with in em_tech and would just be duplicating work. Max doc frequency and putting a focus on also helps so will look at differences in this.
