### ISSUE TITLE
Crashes when data source not found

### ISSUE THREAD

**Issue by IanGrimstead** [datasciencecampus/pyGrams#127]
**Describe the bug**
Stack trace generated rather than 'Could not find data source'

**To Reproduce**
1. Execute `python pygrams.py -ds=USPTO-random-10000`
2. Observe crash with `NoneType`

**Expected behavior**
Report that the data source is not found

**Comment by mshodge** [comment]
@IanGrimstead I can do this if you like.

**Comment by IanGrimstead** [comment]
Go for it @mshodge ! Write a test that snags when it fails and then make it pass etc :)

**Comment by mshodge** [comment]
Done and in new PR.
