### ISSUE TITLE
week-terms count bug

### ISSUE THREAD

**Issue by thanasions** [datasciencecampus/pyGrams#179]
- get rid of redundant modules (ie. focus)
- look at the minimum data structs we need to include
- why did this fail with patstat
- update tests?

**Comment by IanGrimstead** [comment]
Created branch `179-term-counts-bug`

**Comment by IanGrimstead** [comment]
Duh. Linked to wrong branch:
Simplified TFIDF wrapper and reduced memory usage (#176)
See commit https://github.com/datasciencecampus/pyGrams/commit/fc0465a3ee63083a1471320b88d89c4bc45c0e2b
