### ISSUE TITLE
Timeseries computations contain a bug

### ISSUE THREAD

**Issue by thanasions** [datasciencecampus/pyGrams#241]
Periods for each term are not allocated well. They are a column of a sparse matrice's no zero values. However they are zeros too. I have a feeling there are various other bugs there too!

**Comment by IanGrimstead** [comment]
Branch is `241_timeseries_bugs`

**Comment by IanGrimstead** [comment]
From pull request comments: It maybe breaking the tests, haven't checked.
I have a few fixes on the same ticket as i tried to do a lot within one day.
Main bits:
-> TFIDF wrapper - option to pick n best. Works like a charm with 200,000 features. Maybe add a cmd line option or have as default.
-> Bug when subsetting the term-count matrix(tfidf) we needed to apply the same to the dataframe, as we were getting dates out of there!
-> it works with curve fitting for now. Porter may not meet the right 10 period length it needs. May need a sliding window + pick the best score

Feel free to amend, split into more tickets copy paste etc. See you when i'm back!

**Comment by IanGrimstead** [comment]
* TFIDF wrapper - select N best
  * Hard-coded to run `sum` across TFIDF reduce; take top 1/20th of this list
  * Pipeline then runs `sum` again across TFIDF reduce (`self.__tfidf_reduce_obj.extract_ngrams_from_docset(pick_method)`)
