### ISSUE TITLE
python multiplot for publications

### ISSUE THREAD

**Issue by thanasions** [datasciencecampus/pyGrams#318]
# self.get_multiplot(self.__timeseries_quarterly_smoothed, self.__timeseries_quarterly, self.__emergent,
        #                    self.__term_ngrams, lims=self.__lims, category='emergent', method=emergence_index)
        #
        # self.get_multiplot(self.__timeseries_quarterly_smoothed, self.__timeseries_quarterly, self.__declining,
        #                    self.__term_ngrams, lims=self.__lims, category='declining', method=emergence_index)

**Comment by IanGrimstead** [comment]
Covered in #324 with `-o mutiplot`
