### ISSUE TITLE
User guide has wrong defaults for -th and -dh

### ISSUE THREAD

**Issue by sheepworrier** [datasciencecampus/pyGrams#361]
**Describe the bug**
User guide says the default for -th is text and for -dh is date, but this does not match the pygrams.py code.  The -th default is abstract and there is no default for -dh.  Seeing that both had a default I assumed these arguments were not mandatory and missed the line above that says they are.

**Expected behavior**
Suggest you make the line that says they are mandatory bold and update the default values to match the script.

**Comment by thanasions** [comment]
Thank you for the bug issue and the suggestion. We will rectify shortly.

**Comment by thanasions** [comment]
It is now updated to say that abstract is the default text header and None for date header as pyGrams can also work as a keywords extractor without time series analysis. Also made clear that both fields are mandatory with bold letters. Thanks again for the valuable feedback
